#!/usr/bin/env perl
# -*- cperl -*-
# Copyright (c) 2021, MariaDB Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1335  USA

# This program reads sql_yacc.yy and generates sql_yacc_default.yy and
# sql_yacc_oracle.yy
#

my $default_start="Start SQL_MODE_DEFAULT_SPECIFIC";
my $default_end=  "End SQL_MODE_DEFAULT_SPECIFIC";
my $oracle_start= "Start SQL_MODE_ORACLE_SPECIFIC";
my $oracle_end=   "End SQL_MODE_ORACLE_SPECIFIC";
my $in_default= 0;
my $in_oracle= 0;
my $line= 0;
my $start=0;
my $found_end;
my $org_dir=".";
my $res_dir=".";

my $header="/* This file was autogenerated from sql_yacc.yy. Do not edit! */";

if ($#ARGV >= 0)
{
  $org_dir= $ARGV[0];
  $res_dir= $ARGV[1] if ($#ARGV >= 1);
}

unlink("$res_dir/sql_yacc_default.yy");
unlink("$res_dir/sql_yacc_oracle.yy");

open(YACC, '<', "$org_dir/sql_yacc.yy") or die "$1";
open(DEFAULT,'>', "$res_dir/sql_yacc_default.yy") or die "$!";
open(ORACLE,'>', "$res_dir/sql_yacc_oracle.yy") or die "$!";

print DEFAULT "$header\n";
print ORACLE "$header\n";

# Replace copyright with empty lines, to make the header more visible

while (<YACC>)
{
    if (/Boston/)
    {
        $found_end= 1;
        last;
    }
    print DEFAULT "\n";
    print ORACLE "\n";
}
die "Could not find end of copyright statement in sql_yacc.yy" if (!$found_end);

while ($_= <YACC>)
{
    my $found= 0;
    $line++;
    if (/$default_start/)
    {
        if ($in_default or $in_oracle)
        {
            die "Found duplicate '$_' at line $line";
        }
        $in_default= 1;
        $start= $line;
        $found= 1;
    }
    if (/$default_end/)
    {
        if (!$in_default)
        {
            die "Found wrong '$_' at line $line";
        }
        $in_default= 0;
        $found= 1;
    }
    if (/$oracle_start/)
    {
        if ($in_default or $in_oracle)
        {
            die "Found duplicate '$_' at line $line";
        }
        $in_oracle= 1;
        $start= $line;
        $found= 1;
    }
    if (/$oracle_end/)
    {
        if (!$in_oracle)
        {
            die "Found wrong '$_' at line $line";
        }
        $in_oracle= 0;
        $found= 1;
    }

    if ($found)
    {
      print DEFAULT "\n";
      print ORACLE "\n";
    }
    elsif ($in_oracle)
    {
        print ORACLE $_;
        print DEFAULT "\n";
    }
    elsif ($in_default)
    {
        print ORACLE "\n";
        print DEFAULT "$_";
    }
    else
    {
        print ORACLE  "$_";
        print DEFAULT "$_";
    }
}

die "Found no closing of '$default_start' from line $start" if ($in_default);
die "Found no closing of '$oracle_start' from line $start" if ($in_oracle);

close(DEFAULT);
close(ORACLE);

chmod 0444, "$res_dir/sql_yacc_default.yy", "$res_dir/sql_yacc_oracle.yy";
